# Generated by Django 3.1.5 on 2021-01-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210121_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='phone_number',
            field=models.PositiveIntegerField(),
        ),
    ]
