# Generated by Django 3.1.5 on 2021-01-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210121_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='phone_number',
            field=models.PositiveIntegerField(max_length=10),
        ),
    ]
