# Generated by Django 3.1.5 on 2021-01-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210121_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=6),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='phone_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
