# Generated by Django 3.1.5 on 2021-01-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_profilemodel_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='phone_number',
        ),
    ]
