# Generated by Django 3.1.5 on 2021-01-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_profilemodel_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='phone_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
