# Generated by Django 3.1.5 on 2021-01-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_profilemodel_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Male', max_length=6),
        ),
    ]
