# Generated by Django 3.1.5 on 2021-01-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20210127_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Male', max_length=6),
        ),
    ]
