# Generated by Django 3.1.5 on 2021-01-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20210118_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image3',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
