# Generated by Django 3.1.5 on 2021-01-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_auto_20210121_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Automobile', 'Automobile'), ('Groceries', 'Groceries'), ('Health', 'Health')], default='Category', max_length=15, null=True),
        ),
    ]
