# Generated by Django 3.1.5 on 2021-02-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_auto_20210202_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.CharField(choices=[('Groceries', 'Groceries'), ('Health', 'Health'), ('Automobile', 'Automobile'), ('Fashion', 'Fashion')], default='Category', max_length=15, null=True),
        ),
    ]
